name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        make build
        make install

    - name: Run check
      run: make test

    - name: Run distcheck
      run: make lint

    - name: Clean up after build
      if: success()
      run: make clean
